version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: navyasattineni/project_backend:latest
    container_name: backend
    restart: unless-stopped
    environment:
      MONGO_URL: "mongodb://mongo:27017/tutorials_db"
      MONGODB_URI: "mongodb://mongo:27017/tutorials_db"
      PORT: "8080"
    depends_on:
      - mongo
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: navyasattineni/project_frontend:latest
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      API_URL: "http://backend:8080"
    ports:
      - "8081:80"

volumes:
  mongo_data:
